"""empty message

Revision ID: 94eaf540f429
Revises: 6d50f806d935
Create Date: 2022-02-15 18:39:35.375939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94eaf540f429'
down_revision = '6d50f806d935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('favorited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'favorited')
    # ### end Alembic commands ###
